deployment:
  tasks:
    - export DEPLOYPATH=/home/mahg5481/public_html/gano
    - /bin/cp -r * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
